"""Generate docs/SCENARIO_TINY.md (TODO 5.5): the cast of characters, from the database
and id_map, so it never goes stale. Generated: don't edit by hand."""

from collections import defaultdict
from typing import Any

from sqlalchemy import Connection, select

from cam_testdata import db


def _t(name: str) -> Any:
    return db.metadata().tables[name]


def render(
    conn: Connection,
    profile: str,
    id_rows: list[dict[str, str]],
    fhir: dict[str, int],
    features: dict[str, list[str]],
    rows: dict[str, int],
) -> str:
    key_of = {r["id"]: r["handle"].rsplit("/", 1)[-1] for r in id_rows}
    display: dict[str, str] = {
        r[0]: r[1]
        for r in conn.execute(
            select(_t("Concept").c.concept_curie, _t("Concept").c.display)
        )
    }

    def name(curie: str | None) -> str:
        if curie is None:
            return "—"
        return f"{display.get(curie, curie)} (`{curie}`)"

    def key(value: Any) -> str:
        return key_of.get(str(value), str(value))

    lines = [
        f"# Scenario: {profile}",
        "",
        "<!-- Generated by `cam-testdata build --profile tiny` from scenarios/tiny.yaml. Don't edit. -->",
        "",
        (
            f"Source: `scenarios/{profile}.yaml`. IDs are minted from handles "
            f"(`{profile}/<Class>/<key>`); `output/{profile}/id_map.csv` maps every key to its ID."
        ),
        "",
        "## Studies",
        "",
        "| key | ID | title | code | access policy | parent |",
        "|---|---|---|---|---|---|",
    ]
    ap: dict[str, str] = {
        r[0]: r[1]
        for r in conn.execute(
            select(
                _t("AccessPolicy").c.access_policy_id,
                _t("AccessPolicy").c.data_use_permission,
            )
        )
    }
    for s in conn.execute(
        select(_t("Study")).order_by(_t("Study").c.study_id)
    ).mappings():
        lines.append(
            f"| {key(s['study_id'])} | `{s['study_id']}` | {s['study_title']} | {s['study_code']} | "
            f"{key(s['access_policy_id'])}: {name(ap.get(s['access_policy_id']))} | "
            f"{key(s['parent_study']) if s['parent_study'] else '—'} |"
        )

    roles: dict[str, str] = {}
    for m in conn.execute(select(_t("FamilyMembership"))).mappings():
        roles[m["subject_id"]] = f"{key(m['family_id'])}: {name(m['family_role'])}"
    demo = {
        d["subject_id"]: d for d in conn.execute(select(_t("Demographics"))).mappings()
    }
    by_subject: dict[str, dict[str, list[str]]] = defaultdict(lambda: defaultdict(list))
    for e in conn.execute(
        select(_t("Encounter")).order_by(_t("Encounter").c.encounter_id)
    ).mappings():
        by_subject[e["subject_id"]]["Encounters"].append(
            f"{key(e['encounter_id'])} (day {e['age_at_event']})"
        )
    concepts = defaultdict(list)
    for row in conn.execute(select(_t("SubjectAssertion_concept"))).mappings():
        concepts[row["SubjectAssertion_assertion_id"]].append(
            row["concept_concept_curie"]
        )
    values = defaultdict(list)
    for row in conn.execute(select(_t("SubjectAssertion_value_concept"))).mappings():
        values[row["SubjectAssertion_assertion_id"]].append(
            row["value_concept_concept_curie"]
        )
    for a in conn.execute(
        select(_t("SubjectAssertion")).order_by(_t("SubjectAssertion").c.assertion_id)
    ).mappings():
        what = ", ".join(name(c) for c in concepts[a["assertion_id"]])
        if a["value_number"] is not None:
            value = (
                f"{a['value_number']} {display.get(a['value_unit'], a['value_unit'])}"
            )
        else:
            value = (
                ", ".join(display.get(v, v) for v in values[a["assertion_id"]]) or "—"
            )
        by_subject[a["subject_id"]]["Assertions"].append(
            f"{key(a['assertion_id'])}: {what} = {value}"
        )
    for s in conn.execute(
        select(_t("Sample")).order_by(_t("Sample").c.sample_id)
    ).mappings():
        derived = (
            f", from {key(s['parent_sample_id'])}" if s["parent_sample_id"] else ""
        )
        by_subject[s["subject_id"]]["Samples"].append(
            f"{key(s['sample_id'])} ({name(s['sample_type'])}{derived})"
        )
    for f in conn.execute(select(_t("File_subject_id"))).mappings():
        by_subject[f["subject_id_subject_id"]]["Files"].append(key(f["File_file_id"]))

    lines += ["", "## Subjects", ""]
    for s in conn.execute(
        select(_t("Subject")).order_by(
            _t("Subject").c.study_id, _t("Subject").c.subject_id
        )
    ).mappings():
        sid = s["subject_id"]
        d = demo.get(sid)
        lines.append(f"### {key(sid)} (`{sid}`, study {key(s['study_id'])})")
        lines.append("")
        lines.append(f"- Type: {name(s['subject_type'])}")
        if sid in roles:
            lines.append(f"- Family role: {roles[sid]}")
        if d:
            vital = (
                f"; {name(d['vital_status'])} at day {d['age_at_last_vital_status']}"
                if d["vital_status"]
                else ""
            )
            lines.append(
                f"- Sex: {name(d['sex'])}; ethnicity: {name(d['ethnicity'])}{vital}"
            )
        else:
            lines.append("- No Demographics")
        for section in ("Encounters", "Assertions", "Samples", "Files"):
            items = sorted(by_subject[sid][section])
            if items:
                lines.append(f"- {section}: " + "; ".join(items))
        lines.append("")

    lines += [
        "## Expected FHIR resources (by ID prefix)",
        "",
        "| prefix | count |",
        "|---|---|",
    ]
    lines += [f"| `{p}` | {n} |" for p, n in fhir.items()]
    lines += ["", "## Coverage features", "", "| feature | records |", "|---|---|"]
    for feature, keys in sorted(features.items()):
        lines.append(f"| {feature} | {', '.join(k.rsplit('/', 1)[-1] for k in keys)} |")
    lines += ["", "## Row counts", "", "| table | rows |", "|---|---|"]
    lines += [f"| {t} | {n} |" for t, n in rows.items() if n]
    return "\n".join(lines) + "\n"
